In [4]:
import numpy as np

In [5]:
matrix_1 = np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [7]:
matrix_1.shape

(2, 2)

In [10]:
matrix_2 = np.array([[2,3,4],[6,7,8],[4,5,6]])
print(matrix_2)


[[2 3 4]
 [6 7 8]
 [4 5 6]]


In [11]:
matrix_2.shape

(3, 3)

Matrix with random values

In [34]:
random_matrix = np.random.rand(2,3)

print(random_matrix)

[[0.17177    0.16551342 0.47090101]
 [0.15545623 0.44257055 0.12569513]]


Creatting matrix with random variable

In [17]:
random_integer_matrix = np.random.randint(100, size = (4,5))

print(random_integer_matrix)

[[85 63 53 20 23]
 [ 9 58 87 96  4]
 [86 79 30 25 21]
 [ 9 34 62 81 67]]


Matrix with all values 1

In [19]:
matrix_3 = np.ones((2,3), dtype = int )
print(matrix_3)

[[1 1 1]
 [1 1 1]]


null matrix or zero matrix

In [22]:
null_matrix = np.zeros((4,4), dtype = int)
print(null_matrix)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


Identity Matrix

In [25]:
identity_matrix = np.eye(3, 4, dtype = int)
print(identity_matrix)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


Transpose of a matrix

In [26]:
matrix = np.random.randint(100, size = (4,5), dtype = int)
print(matrix)

[[62 39 57  5 40]
 [ 0 73 86 83 19]
 [58 75 28  5 48]
 [27 53 58 92 33]]


In [29]:
print(matrix[ : , 0])

[62  0 58 27]


In [30]:
transpose_matrix = np.transpose(matrix)
print(transpose_matrix)

[[62  0 58 27]
 [39 73 75 53]
 [57 86 28 58]
 [ 5 83  5 92]
 [40 19 48 33]]


In [32]:
print(transpose_matrix[ : , 0])


[62 39 57  5 40]


matrix addition

In [40]:
a = np.array([ [2,3] , [4,5] ])
b = np.array([ [6,7] , [8,9] ])

a_plus_b = a++b

print(a_plus_b)

[[ 8 10]
 [12 14]]


In [41]:
sum = np.add(a,b)
print(sum)

[[ 8 10]
 [12 14]]


In [42]:
sum = np.subtract(a,b)
print(sum)

[[-4 -4]
 [-4 -4]]


In [44]:
a = np.random.randint(100, size = (3,4), dtype = int)
b = np.random.randint(100, size = (3,4), dtype = int)

In [45]:
a.shape

(3, 4)

In [46]:
b.shape

(3, 4)

In [47]:
a+b

array([[115, 138, 155,  92],
       [ 92,  85,  61, 123],
       [102, 176,  41, 126]])

Matrix multiplication by scaler

In [51]:
a = np.random.randint(100, size = (3,4), dtype = int)
c = 5
b = a*c

In [52]:
b

array([[ 80, 410, 170,   0],
       [270, 310,  75, 215],
       [135, 275, 290, 215]])

In [53]:
a

array([[16, 82, 34,  0],
       [54, 62, 15, 43],
       [27, 55, 58, 43]])

In [54]:
b = np.multiply(a,c)

In [55]:
b

array([[ 80, 410, 170,   0],
       [270, 310,  75, 215],
       [135, 275, 290, 215]])

Multiplying 2 matrices